### ISSUE TITLE
"Drag and Drop" option to the "Upload Files" tab in FilePicker stopped accepting dropped files

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1037]
#### Category
[ ] Enhancement
[X] Bug
[ ] Question

#### Version

Please specify what version of the library you are using: [  3.3.0 ]

#### Expected / Desired Behavior / Question
"Drag and Drop" option to the "Upload Files" tab in FilePicker should use dropped files from explorer.
#### Observed Behavior
dropped files do nothing to the control
![image](https://user-images.githubusercontent.com/5054931/136294747-2e9f1bd9-7e11-4cdf-85ac-f728ccf9d5c0.png)

I think previous versions did wok

#### Steps to Reproduce

may code is:
` <FilePicker label='Files to add' buttonLabel={'Add Files'}
                includePageLibraries={false} hideLocalUploadTab hideOrganisationalAssetTab // 
                hideRecentTab hideStockImages storeLastActiveTab={true} 
                onSave={_onFilePickerSave} hideSiteFilesTab
                context={props.context} required  
            />`
maybe I need to change a property?

Thanks!

**Comment by Ofer-Gal** [comment]
If it helps, here is the error from the dev tools
`TypeError: Cannot read properties of null (reading 'isDirectory')
    at DragDropFiles.<anonymous> (https://localhost:4321/dist/ace-dpc-request-web-part.js:14586:47)
    at step (https://localhost:4321/dist/ace-dpc-request-web-part.js:14471:23)
    at Object.next (https://localhost:4321/dist/ace-dpc-request-web-part.js:14452:53)
    at https://localhost:4321/dist/ace-dpc-request-web-part.js:14446:71
    at new Promise (<anonymous>)
    at ./node_modules/@pnp/spfx-controls-react/lib/controls/dragDropFiles/DragDropFiles.js.__awaiter (https://localhost:4321/dist/ace-dpc-request-web-part.js:14442:12)
    at DragDropFiles._this.getFilesAsync (https://localhost:4321/dist/ace-dpc-request-web-part.js:14554:53)
    at DragDropFiles.<anonymous> (https://localhost:4321/dist/ace-dpc-request-web-part.js:14538:51)
    at step (https://localhost:4321/dist/ace-dpc-request-web-part.js:14471:23)
    at Object.next (https://localhost:4321/dist/ace-dpc-request-web-part.js:14452:53)`
