### ISSUE TITLE
serviceScope={serviceScope from AppContext} Does not pass typescript in SPFx 1.15

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1253]
#### Category
[ ] Enhancement

[? ] Bug

[ ?] Question

#### Version 3.8.1

Using
```
    const { wpContext } = React.useContext(AppContext);
    const sp:ServiceScope = wpContext.serviceScope;
```
I get TS error:
```
TS2322: Type 'import("C:/DATA/Sources/Repos/SPFx15/DpcAllJobsScreen/node_modules/@microsoft/sp-core-library/dist/index-internal").ServiceScope' is not assignable to type 'import("C:/DATA/Sources/Repos/SPFx15/DpcAllJobsScreen/node_modules/@pnp/spfx-property-controls/node_modules/@microsoft/sp-core-library/dist/index-internal").ServiceScope'.
  Types have separate declarations of a private property '_registrations'.
    163 |     const sp:ServiceScope = wpContext.serviceScope;
    164 |     return (
  > 165 |         <LivePersona upn={params.data.RequestFor.Email}  serviceScope={sp}
        |                                                          ^^^^^^^^^^^^
```
How can I use "LivePersona" with hooks deep in child component?
what is "private property '_registrations"

Thanks

**Comment by AJIXuMuK** [comment]
@Ofer-Gal  - the library hasn't been updated to SPFx 1.15.0 yet.
You should cast the property to `any` to pass it in.
Or, potentially, do double casting like `as unknown as ServiceScope` where `ServiceScope` is imported as `type` from `@pnp/spfx-property-controls/node_modules/@microsoft/sp-core-library` (not sure though it will work)

**Comment by Ofer-Gal** [comment]
@AJIXuMuK - Thank you. Both your suggestions worked for TS but the run time failed with error:
```
SPLoaderError.loadComponentError]:
Failed to load component "ee96f3dd-120e-4983-b269-ac5da936bad1" (DpcAllJobsScreenWebPart). Original error: The entry point for component "ee96f3dd-120e-4983-b269-ac5da936bad1" (DpcAllJobsScreenWebPart) has a dependency on "@microsoft/sp-loader" that is not declared in the manifest.

INNERERROR:
The entry point for component "ee96f3dd-120e-4983-b269-ac5da936bad1" (DpcAllJobsScreenWebPart) has a dependency on "@microsoft/sp-loader" that is not declared in the manifest.
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_d773573f7d35b6f7a679f16c44d839ae.js:70:214899)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_d773573f7d35b6f7a679f16c44d839ae.js:72:7680)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_d773573f7d35b6f7a679f16c44d839ae.js:72:44944)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-webpart-workbench-assembly_en-us_d773573f7d35b6f7a679f16c44d839ae.js:72:41035)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_dc58eaaa7aaff14eda18.js:1:6012
```

So I will wait for you to add SPFx 1.15 support. I will use MGT for now.
Any idea when you will do it?

**Comment by AJIXuMuK** [comment]
@Ofer-Gal the issue doesn't seem to be related to 1.15. Have you tried the same with 1.14? Is it working?

**Comment by fonbrauzen** [comment]
@AJIXuMuK any plans, or estimations about when 1.15 will be integrated?

**Comment by michaelmaillot** [comment]
Hi everyone,

Latest version (3.15.0) is based on SPFx 1.17.3.

Did anyone of you had the chance to test again with this one? Does the problem still occur?
