### ISSUE TITLE
DateTimeControl throws exception when value is undefined, although undefined can be expected through props

### ISSUE THREAD

**Issue by Link631** [pnp/sp-dev-fx-controls-react#1366]
**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

#### Version 

Please specify what version of the library you are using: [     3.12.0    ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question

I am using a DateTimePicker

<DateTimePicker value = {undefined}/>....

The Properties allow a value undefined, cause the type is defined as : Date | undefined

#### Observed Behavior
An exception occurs in Chrome:

TypeError: Cannot read properties of null (reading 'getTime')
    at DateTimePicker._this.validate (DateTimePicker.js:150:1)
    at invokeFunction (Async.js:310:1)....

#### Steps to Reproduce
1. Create a spfx webpart project
2. install latest version of spfx controls react
3. return an component, which just renders the DateTimePicker with value undefined.

#### Expected ####
The component should render the picker and should not have a value.

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by Link631** [comment]
The problem only appears, when the dateConvention is set to DateTime.

So: DateTimeConvention = DateTime plus Value = undefined leads in an error.

DateTimeConvention = Date and Value = undefined does work.

My workaround now will be to force DateTimeConvention to be Date in case the value is undefined. But: It should also work with DateTime... I think.

**Comment by michaelmaillot** [comment]
Hi @Link631,

I confirm I can repro this one but only if `onGetErrorMessage` prop is used. And I agree with you, it should work with any kind of DateConvention value.
