### ISSUE TITLE
DynamicForm webAbsoluteUrl setting causes error

### ISSUE THREAD

**Issue by IRRDC** [pnp/sp-dev-fx-controls-react#1437]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.11.0]

#### Expected / Desired Behavior / Question
The feature to provide a webAbsoluteUrl that got added here https://github.com/pnp/sp-dev-fx-controls-react/pull/1244 does not seem to work anymore. Providing a webAbsoluteUrl to the same site does not cause any issues, providing one to a different site will throw a "List does not exist." error even though the list id is correct and the user has permissions to access the provided site:

Uncaught Error Error: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-2130575322, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"List does not exist.\n\nThe page you selected contains a list that does not exist.  It may have been deleted by another user."}}}
    at HttpRequestError (...\dist\node_modules\@pnp\odata\dist\odata.es5.js:93:1)
    at <anonymous> (...\dist\node_modules\@pnp\odata\dist\odata.es5.js:102:1)

#### Observed Behavior
Can't show a form for a list in another site.

#### Steps to Reproduce
Use a PropertyFieldSitePicker and a PropertyFieldListPicker to select list and site and forward data to a DynamicForm.

**Comment by IRRDC** [comment]
The problem was in another control and not dynamicform.
