### ISSUE TITLE
Cannot read properties of null (reading 'value') at DynamicForm.js:480:1

### ISSUE THREAD

**Issue by codingsisya** [pnp/sp-dev-fx-controls-react#1481]
#### Category
[ ] Bug

#### Version
Latest version 3.13.0
SPFx - 1.16.0

#### Expected / Desired Behavior / Question
Should load the new form for configured list

#### Observed Behavior
Doesn't load new form. Throws error in console as below 
![image](https://user-images.githubusercontent.com/53614457/222346329-92a3ffab-873b-4772-9aa0-fc2d9bb71c2e.png)

Error get field informations TypeError: Cannot read properties of null (reading 'value')
    at DynamicForm.js:480:1
    at step (DynamicForm.js:57:1)
    at Object.next (DynamicForm.js:38:17)
    at step (DynamicForm.js:42:1)
    at Object.next (DynamicForm.js:38:17)
    at fulfilled (DynamicForm.js:29:1)

#### Steps to Reproduce
Create a list with MMD field pointing to a termset. Configure the list in form customizer config. 
Run gulp serve

Thanks!

**Comment by codingsisya** [comment]
Please note that the error disappears and form loads as expected when we remove the MMD field.

**Comment by codingsisya** [comment]
The below issue is same as mine. Fix has been merged. Hopefully, we see it in next release. But this is a blocker for now. 
https://github.com/pnp/sp-dev-fx-controls-react/issues/1422
