### ISSUE TITLE
Dynamic Form: Error get field informations Error: Error making HttpClient request in queryable [404]  ::>

### ISSUE THREAD

**Issue by manuhinCCS** [pnp/sp-dev-fx-controls-react#1503]
Getting below error in Dynamic Form.

![image](https://user-images.githubusercontent.com/112081775/229833088-b102f875-70d4-4b5a-8c6f-0a07c8930ced.png)

Dynamic  Form not loading.
![image](https://user-images.githubusercontent.com/112081775/229834163-a245f9c4-2f37-4332-a2a2-d76c2bce15a0.png)

Version: "@pnp/spfx-controls-react": "^3.9.0",
Code: 
{(this.state.ListID !== "" && this.state.contentTypeId !== "") &&

                    <DynamicForm
                        context={this.props.context as any}
                        listId={this.state.ListID}
                        contentTypeId={this.state.contentTypeId}
                        listItemId={this.state.ItemId !== null ? this.state.ItemId : 0}
                        returnListItemInstanceOnSubmit={true}
                        //   onCancelled={this.OnCancel}
                        onBeforeSubmit={this.onBeforeSubmit}
                        disabled={this.state.disableDynamic}
                        onSubmitError={(listItem, error) => { console.log(error) }}
                        onSubmitted={this.onSubmitted}
                        disabledFields={["TemporaryContract"]}
                        fieldOverrides={{
                            "Title": this.renderTitle,
                            // "Approvers": this.renderApprover,
                            // "Reviewers": this.renderReviewer
                        }}
                    >
                    </DynamicForm>}

Getting 404
 GET https://XXXXXX.sharepoint.com/sites/ABC/SitePages/_api/web/lists('38823001-10ba-4bf1-8107-74d111e25820')/items(1799) 404
YmBQ.FetchClient.fetch @ net.js:35
retry @ sphttpclient.js:95
(anonymous) @ sphttpclient.js:114
clU1.SPHttpClient.fetchRaw @ sphttpclient.js:113
(anonymous) @ sphttpclient.js:58
step @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
clU1.SPHttpClient.fetch @ sphttpclient.js:25
(anonymous) @ pipeline.js:161
TZA7.PipelineMethods.send @ pipeline.js:144
descriptor.value @ pipeline.js:76
next @ pipeline.js:34
(anonymous) @ pipeline.js:76
Promise.then (async)
descriptor.value @ pipeline.js:76
next @ pipeline.js:34
(anonymous) @ pipeline.js:76
Promise.then (async)
descriptor.value @ pipeline.js:76
next @ pipeline.js:34
pipe @ pipeline.js:46
(anonymous) @ pipeline-binder.js:14
(anonymous) @ operations.js:28
step @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
(anonymous) @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
(anonymous) @ operations.js:13
spGet @ operations.js:50
ncXi._SharePointQueryable.get @ sharepointqueryable.js:103
(anonymous) @ DynamicForm.js:403
step @ DynamicForm.js:58
(anonymous) @ DynamicForm.js:39
fulfilled @ DynamicForm.js:30
Promise.then (async)
step @ DynamicForm.js:32
(anonymous) @ DynamicForm.js:33
WgIJ.__awaiter @ DynamicForm.js:29
DynamicForm._this.getFieldInformations @ DynamicForm.js:387
WgIJ.DynamicForm.componentDidMount @ DynamicForm.js:752
ss @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
hc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Zs @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
enqueueSetState @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
y.setState @ react-16-bundle_none_7c853fe1c9f3209f62bb.js:2
(anonymous) @ DynamicForms.tsx:47
Promise.then (async)
(anonymous) @ DynamicForms.tsx:43
Promise.then (async)
QdjX.DynamicForms._getListGuid @ DynamicForms.tsx:40
(anonymous) @ DynamicForms.tsx:27
step @ TenantWorkIcon.js:30
(anonymous) @ TenantWorkIcon.js:30
(anonymous) @ TenantWorkIcon.js:30
QdjX.__awaiter @ TenantWorkIcon.js:30
QdjX.DynamicForms.componentDidMount @ DynamicForms.tsx:26
ss @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
hc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Zs @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
enqueueSetState @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
y.setState @ react-16-bundle_none_7c853fe1c9f3209f62bb.js:2
(anonymous) @ ContractUpload.tsx:303
step @ contract-index-web-part.js:479308
(anonymous) @ contract-index-web-part.js:479289
fulfilled @ contract-index-web-part.js:479280
Promise.then (async)
step @ contract-index-web-part.js:479282
(anonymous) @ contract-index-web-part.js:479283
r90l.__awaiter @ contract-index-web-part.js:479279
r90l.ContractUpload._bindDraftData @ ContractUpload.tsx:205
(anonymous) @ ContractUpload.tsx:198
Promise.then (async)
(anonymous) @ ContractUpload.tsx:195
step @ contract-index-web-part.js:479308
(anonymous) @ contract-index-web-part.js:479289
(anonymous) @ contract-index-web-part.js:479283
r90l.__awaiter @ contract-index-web-part.js:479279
(anonymous) @ ContractUpload.tsx:187
Promise.then (async)
(anonymous) @ ContractUpload.tsx:187
step @ contract-index-web-part.js:479308
(anonymous) @ contract-index-web-part.js:479289
(anonymous) @ contract-index-web-part.js:479283
r90l.__awaiter @ contract-index-web-part.js:479279
r90l.ContractUpload.getdata @ ContractUpload.tsx:184
(anonymous) @ ContractUpload.tsx:180
step @ contract-index-web-part.js:479308
(anonymous) @ contract-index-web-part.js:479289
(anonymous) @ contract-index-web-part.js:479283
r90l.__awaiter @ contract-index-web-part.js:479279
(anonymous) @ ContractUpload.tsx:163
Promise.then (async)
(anonymous) @ ContractUpload.tsx:163
step @ contract-index-web-part.js:479308
(anonymous) @ contract-index-web-part.js:479289
(anonymous) @ contract-index-web-part.js:479283
r90l.__awaiter @ contract-index-web-part.js:479279
r90l.ContractUpload.getUserMessageSettings @ ContractUpload.tsx:161
r90l.ContractUpload.componentDidUpdate @ ContractUpload.tsx:156
ss @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
hc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Zs @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
enqueueSetState @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
y.setState @ react-16-bundle_none_7c853fe1c9f3209f62bb.js:2
(anonymous) @ ContractIndex.tsx:197
Promise.then (async)
(anonymous) @ ContractIndex.tsx:196
step @ SkeletonText.js:33
(anonymous) @ SkeletonText.js:33
(anonymous) @ SkeletonText.js:33
RDda.__awaiter @ SkeletonText.js:33
RDda.ContractIndex.componentDidMount @ ContractIndex.tsx:194
ss @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
hc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Zs @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Bc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
rc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Wc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.render @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
VLw2.ContractIndexWebPart.render @ ContractIndexWebPart.ts:54
t._renderWithAccessibleTitle @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
t._onInViewport @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
t._internalFirstTimeRender @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
e._renderWebPart @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
e.loadWebPart @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
Promise.then (async)
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
ms @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Lc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ki @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ac @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
hc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Ki @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Qi @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
qi @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
uc @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
Lo @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:69
onInViewport @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
_renderComponentInViewport @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
release @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
_releaseTarget @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
(anonymous) @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
releaseComponentsInPreloadArea @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
_handleScroll @ sp-pages-assembly_en-us_ba227f1d6327159249f551b072cc409b.js:70
DynamicForm.js:646 Error get field informations Error: Error making HttpClient request in queryable [404]  ::> 
    at new HttpRequestError (parsers.js:130:1)
    at Function.<anonymous> (parsers.js:145:1)
    at step (tslib.es6.js:102:1)
    at Object.next (tslib.es6.js:83:45)
    at fulfilled (tslib.es6.js:73:42)

Thanks!

**Comment by manuhinCCS** [comment]
Tried with below code, but still facing issue.

<DynamicForm
                        context={this.props.context as any}
                        listId={this.state.ListID}
                        contentTypeId={this.state.contentTypeId}
                        listItemId={this.state.ItemId !== null ? this.state.ItemId : 0}
                        returnListItemInstanceOnSubmit={true}
                        disabled={this.state.disableDynamic}
                        onSubmitError={(listItem, error) => { console.log(error) }}
                        onSubmitted={async (listItemData) => { console.log(listItemData); }}
                        fieldOverrides={{
                            "Title": this.renderTitle,
                        }}
