### ISSUE TITLE
Adding ListView to component causes crash 

### ISSUE THREAD

**Issue by geoffbarcalow** [pnp/sp-dev-fx-controls-react#849]
I had previously gotten the ListView to work a little over a week ago with SPFx v1.11 and pnp/sp-dev-fx-controls-react v2.5 But today, with SPFx v1.12 and controls v3 I can't get it to work. As soon as I try to render ListView with or without props it crashes.

#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: 
Windows 10
SPFx v1.12 
@pnp/sp-dev-fx-controls-react v3
gulp CLI version: 2.3.0
gulp Local version: 4.0.2
node v10.24.0

#### Expected / Desired Behavior / Question
I expected to be able to add a <ListView .../> to the package.

#### Observed Behavior
The component crashes, there are several errors in the console that are not there if I remove the reference to <ListView/>

```
sp-webpart-workbench-assembly_default.js:40450 [1616706238683][SPComponentLoader.loadComponen] Error: loadComponentMaxRetriesError

Uncaught (in promise) Event {isTrusted: true, type: "error", target: link, currentTarget: null, eventPhase: 0, …}

[1616706239858][WebPartZone.didMount.load] [SPLoaderError.loadComponentError]:
loadComponentError

spErrorInnerErrorText
loadEntryPointError
spErrorCallStackText
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:38476:23)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:52330:28)
    at Function.ff4n.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:54879:21)
    at Function.ff4n.ErrorBuilder.buildLoadComponentError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_default.js:54748:21)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/chunk.systemjs-component-loader_default_283544c8d416b214f73b.js:1025:75
```

#### Steps to Reproduce
1) > yo @microsoft/sharepoint
2) > npm i @pnp/sp-dev-fx-controls-react@3.0
4) > Modify the react component like so:
`  public render(): React.ReactElement<IListViewTestProps> {
    let rows = [
      {col1: "1",col2: "2",col3: "3"},
      {col1: "4",col2: "5",col3: "6",},
    ];
    return <ListView items={rows} />;
  }
`
5) > gulp serve

**Comment by AJIXuMuK** [comment]
Hi @geoffbarcalow,
Thank you for reporting the issue.
SPFx 1.12 has been deprecated for now.
Please use SPFx 1.11 and Controls `v2` until new release.
